# 服务端口
server:
  port: 8006

#不同环境的配置文件选择
spring:
  application:
    name: api-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.130.47:3306/springcloud02?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: qwer1234


# mybatis配置
mybatis:
  type-aliases-package: com.z7.springcloud.pojo
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

# eureka注册服务
eureka:
  client:
    service-url:  # 监控页面
      defaultZone: http://eureka8003.com:8003/eureka/
  instance:
    instance-id: api-server-b # 修改eureka上的默认描叙信息
    prefer-ip-address: true #显示ip地址
# 完善注册服务信息
info:
  app.name: z7-spring-cloud-eureka
  author.name: z7-x
