# 服务端口
server:
  port: 8005

#不同环境的配置文件选择
spring:
  application:
    name: api-eureka-c

# eureka配置
eureka:
  instance:
    hostname: eureka8005.com # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # 如果为false则表示自己为注册中心
    service-url:  # 监控页面
      defaultZone: http://eureka8003.com:8003/eureka/,http://eureka8004.com:8004/eureka/
